### ISSUE TITLE
Desktop Organizer

### ISSUE THREAD

**Issue by DevChoganwala** [MSTC-DA-IICT/OpenScripts#1]
## **Description**

Create a script to organize your desktop directory based on different types of files i.e. place similar types of files in a single directory. 

For example: All the images can be put in a folder named images

## **Requirements**

Your script should **at-least** work for the following types of files:

- [x] Images
- [x] PDFs
- [x] Text documents
- [x] videos

**Comment by KrishPatel10** [comment]
Can I work on this?

**Comment by DevChoganwala** [comment]
Assigned to you @KrishPatel10! Good Luck!!

**Comment by KrishPatel10** [comment]
@DevChoganwala I have completed code as per requirements, In short time after adding some more features i will submit it
