### ISSUE TITLE
Vaccine Availability Tracker

### ISSUE THREAD

**Issue by DevChoganwala** [MSTC-DA-IICT/OpenScripts#3]
## **Description**

Write a script to output all the vaccine centers where vaccine slots are available, given pin-code, vaccine and dose number.

## **Requirements**

Output should **at-least** contain the following fields:

- [x] center name
- [x] address
- [x] fee
- [x] slots
- [x] dose quantity available

**Comment by rahulvansh66** [comment]
@DevChoganwala I sent PR, kindly check it.
