### ISSUE TITLE
Send batch emails

### ISSUE THREAD

**Issue by DevChoganwala** [MSTC-DA-IICT/OpenScripts#5]
## **Description**

Write a script to send emails to all the email-ids listed in a spreadsheet, the email should display html from a html file.

## **Requirements**

- [x] Both spreadsheet and html file paths are to be taken from the user

**Comment by Ronak-Jethava** [comment]
@DevChoganwala 
I want to take up this issue. Can I be assigned to it ?

**Comment by DevChoganwala** [comment]
Assigned to you @Ronak-Jethava . Good Luck 👍
